/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.uvic.seng330.ex9;

import java.io.IOException;
import java.time.LocalDate;
import java.util.List;

public class Driver {

  public static void main(String[] args) {

    CsvParser<ObservedWhale> parser = new CsvParser<>(ObservedWhale.class, "observations.csv");


    try {
      List<ObservedWhale> obs = parser.parseToList();

      System.out.println("Observation List:");
      obs.forEach(System.out::println);

      CountWhales count = new CountWhales(obs);
      System.out.println("There  " + count.beforeDate(LocalDate.of(2007, 6, 1)) + " observations of whales since 2007-06-01");

      SortWhales sortedList = new SortWhales(obs);
      System.out.println("\nHeavier Whale : " + SortWhales.findHeavierWhale(obs.get(0),obs.get(1)).getWeight());
      System.out.println("\nAfter Sorting");
      sortedList.byWeight();
      sortedList.getList().forEach(System.out::println);

      obs.removeIf(ObservedWhale::orcaTest);

      System.out.println("\nAfter Orca Filter:");
      obs.forEach(System.out::println);
    } catch (IOException e) {
      e.printStackTrace();
    }

  }
}