/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.uvic.seng330.ex8;

import org.junit.jupiter.api.Test;


class DriverTest {
    @Test void appHasAGreeting() {
        Driver classUnderTest = new Driver();
    }

}
